### ISSUE TITLE
ParseError: Attributes need to be unique

### ISSUE THREAD

**Issue by krishanik** [matyunya/smelte-template#3]
```
git clone git@github.com:matyunya/smelte-template.git && cd smelte-template && npm i && npm run dev
```

```
rollup v1.31.1
bundles src/main.js → public/bundle.js...
[!] (plugin svelte) ParseError: Attributes need to be unique
node_modules/smelte/src/components/TextField/TextField.svelte
234:       {hint}
235:       {error}
236:       {hint} />
           ^
237:   {/if}
238: </div>
ParseError: Attributes need to be unique
    at error (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$1.error (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/index.ts:93:3)
    at check_unique (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/state/tag.ts:293:11)
    at read_attribute (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/state/tag.ts:323:4)
    at tag (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/state/tag.ts:160:22)
    at new Parser$1 (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/index.ts:45:12)
    at parse (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/parse/index.ts:208:17)
    at compile (/Users/ikrishanik/repos/smelte-template/node_modules/svelte/src/compiler/compile/index.ts:79:14)
    at /Users/ikrishanik/repos/smelte-template/node_modules/rollup-plugin-svelte/index.js:252:22
    at async Promise.all (index 0)
```

**Comment by matyunya** [comment]
Thank you! I've upgraded the template to use rollup-plugin-smelte and latest version of Smelte
